# Generated by Django 5.0.7 on 2024-07-30 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome_completo',
        ),
    ]
