# Generated by Django 5.0.7 on 2024-07-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
