# Generated by Django 5.0.7 on 2024-07-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_remove_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
    ]
